db {
  dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
  dataSource {
    user = "saga_user"
    password = "saga_password"
    databaseName = "saga_db"
    portNumber = 5433
    serverName = localhost
  }
}
